- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker and related tools
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-v2
      - docker-buildx-plugin
    state: present

- name: Ensure Docker running
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true
