node_exporter_version: '1.10.2'
node_exporter_user: 'node_exporter'
node_exporter_install_dir: '/usr/local/bin'
node_exporter_tmp_dir: '/tmp'
node_exporter_archive: 'node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz'
